"""Update account and invite model

Revision ID: ac85daa3abe4
Revises: beba00d33bf3
Create Date: 2026-07-08 10:50:03.657189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac85daa3abe4'
down_revision: Union[str, None] = 'beba00d33bf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('invites', sa.Column('token_hash', sa.String(length=128), nullable=False))
    op.drop_constraint(op.f('invites_token_key'), 'invites', type_='unique')
    op.create_unique_constraint(None, 'invites', ['token_hash'])
    op.drop_column('invites', 'token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invites', sa.Column('token', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'invites', type_='unique')
    op.create_unique_constraint(op.f('invites_token_key'), 'invites', ['token'], postgresql_nulls_not_distinct=False)
    op.drop_column('invites', 'token_hash')
    op.alter_column('accounts', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
